# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_key', models.CharField(db_index=True, max_length=40, verbose_name='Chave do Contrato')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_p', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do contrato',
                'verbose_name_plural': 'Itens dos contratos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contratoitem',
            unique_together=set([('contrato_key', 'produto')]),
        ),
    ]
