# Generated by Django 2.0.3 on 2018-05-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateTimeField(auto_now_add=True, verbose_name='modificado em')),
                ('imagem', models.ImageField(blank=True, db_column='Imagem', null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_f', models.CharField(db_column='Nome_F', max_length=100, unique=True)),
                ('email_f', models.CharField(blank=True, db_column='Email_F', max_length=100, null=True)),
                ('endereco_f', models.CharField(db_column='Endereco_F', max_length=255)),
                ('telefoneprincipal', models.IntegerField(db_column='TelefonePrincipal')),
                ('telefonesecundario', models.IntegerField(blank=True, db_column='TelefoneSecundario', null=True)),
                ('categoria_f', models.CharField(db_column='Categoria_F', max_length=100)),
            ],
            options={
                'db_table': 'Fornecedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_p', models.AutoField(db_column='Codigo_P', primary_key=True, serialize=False)),
                ('nome_p', models.CharField(db_column='Nome_P', max_length=100, verbose_name='Nome do produto')),
                ('quantidade', models.SmallIntegerField(db_column='Quantidade', verbose_name='Quantidade')),
                ('imagem', models.ImageField(db_column='Imagem', upload_to='media', verbose_name='Imagem')),
                ('descricao', models.TextField(db_column='Descricao_P', verbose_name='Descrição')),
                ('custo_p', models.DecimalField(db_column='Custo_P', decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('preco_p', models.DecimalField(db_column='Preço_P', decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('vender', models.BooleanField(db_column='Vender', default=True)),
                ('ativo', models.BooleanField(db_column='Ativo', default=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateTimeField(auto_now_add=True, verbose_name='modificado em')),
                ('categoria_p', models.ForeignKey(db_column='categoria_p', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Categoria')),
                ('nome_f', models.ForeignKey(db_column='Nome Fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'Produto',
                'ordering': ['nome_p'],
                'managed': True,
            },
        ),
    ]
