# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(db_column='alutra', decimal_places=3, max_digits=10, verbose_name='Altura(cm)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(db_column='comprimeito', decimal_places=3, max_digits=10, verbose_name='Comprimento(cm)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(db_column='largura', decimal_places=3, max_digits=10, verbose_name='largura(cm)'),
        ),
    ]
