# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='altura',
            field=models.CharField(db_column='altura', max_length=10, verbose_name='Altura(mts)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comprimento',
            field=models.CharField(db_column='comprimento', max_length=10, verbose_name='Comprimento(mts)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.CharField(db_column='largura', max_length=10, verbose_name='largura(mts)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(db_column='peso', decimal_places=2, max_digits=10, verbose_name='Peso(kg)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_de_itens',
            field=models.SmallIntegerField(db_column='Quantidade de Itens', verbose_name='Quantidade de itens do kit'),
        ),
    ]
