# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(db_column='alutra', decimal_places=2, default=1, max_digits=10, verbose_name='Altura em cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(db_column='comprimeito', decimal_places=2, default=1, max_digits=10, verbose_name='comprimeito em cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(db_column='largura', decimal_places=2, default=1, max_digits=10, verbose_name='largura em cm'),
            preserve_default=False,
        ),
    ]
