# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20181118_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(db_column='peso', decimal_places=4, max_digits=10, verbose_name='Peso(kg)'),
        ),
    ]
