# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20181004_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(db_column='peso', decimal_places=3, max_digits=10, verbose_name='Peso(kg)'),
        ),
    ]
