# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180827_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria_f',
            field=models.CharField(db_column='Categoria_F', max_length=100, verbose_name='Categoria de produtos'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email_f',
            field=models.CharField(blank=True, db_column='Email_F', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco_f',
            field=models.CharField(db_column='Endereco_F', max_length=255, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_f',
            field=models.CharField(db_column='Nome_F', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefoneprincipal',
            field=models.IntegerField(db_column='TelefonePrincipal', verbose_name='Telefone principal'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefonesecundario',
            field=models.IntegerField(blank=True, db_column='TelefoneSecundario', null=True, verbose_name='Telefone Secundário'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_p',
            field=models.AutoField(db_column='Codigo_P', primary_key=True, serialize=False, verbose_name='código produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(db_column='Imagem', null='True', upload_to='media', verbose_name='Imagem'),
        ),
    ]
