# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181005_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(db_column='alutra', decimal_places=3, max_digits=10, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(db_column='comprimeito', decimal_places=3, max_digits=10, verbose_name='comprimeito'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(db_column='largura', decimal_places=3, max_digits=10, verbose_name='largura'),
        ),
    ]
