# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20180910_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(db_column='Imagem', default=1, upload_to='produtos', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
