# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20180911_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(db_column='Imagem', upload_to='media', verbose_name='Imagem'),
        ),
    ]
