# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('nome_c', models.CharField(db_column='Nome_C', max_length=100)),
                ('codigo_c', models.AutoField(db_column='Codigo_C', primary_key=True, serialize=False)),
                ('telefone_c', models.IntegerField(db_column='Telefone_C')),
            ],
            options={
                'db_table': 'Colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(db_column='Descricao')),
                ('dia', models.DateField(db_column='Dia')),
                ('hora', models.TimeField(db_column='Hora')),
                ('endereco_ct', models.CharField(db_column='Endereco_CT', max_length=100)),
            ],
            options={
                'db_table': 'Contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('nome_f', models.CharField(db_column='Nome_F', max_length=100, primary_key=True, serialize=False, verbose_name='Nome do Fornecedor')),
                ('email_f', models.CharField(blank=True, db_column='Email_F', max_length=100, null=True)),
                ('endereco_f', models.CharField(db_column='Endereco_F', max_length=255)),
                ('telefoneprincipal', models.IntegerField(db_column='TelefonePrincipal')),
                ('telefonesecundario', models.IntegerField(blank=True, db_column='TelefoneSecundario', null=True)),
                ('categoria_f', models.CharField(db_column='Categoria_F', max_length=100)),
            ],
            options={
                'db_table': 'Fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_u', models.AutoField(db_column='Codigo_U', primary_key=True, serialize=False)),
                ('nome_u', models.CharField(db_column='Nome_U', max_length=255)),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=100)),
                ('email_u', models.CharField(blank=True, db_column='Email_U', max_length=100, null=True)),
                ('cpf', models.IntegerField(db_column='CPF', unique=True)),
                ('telefone_u', models.IntegerField(db_column='Telefone_U')),
                ('endereco_u', models.CharField(db_column='Endereco_U', max_length=255)),
                ('news', models.NullBooleanField(db_column='News')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_p', models.AutoField(db_column='Codigo_P', primary_key=True, serialize=False, verbose_name='Codigo do produto')),
                ('nome_p', models.CharField(db_column='Nome_P', max_length=100, verbose_name='Titulo do produto')),
                ('quantidade', models.SmallIntegerField(db_column='Quantidade', verbose_name='Quantidade')),
                ('categoria_p', models.CharField(db_column='Categoria_P', max_length=100, verbose_name='Categoria')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banco_de_imagens', verbose_name='Imagem do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Especificação do produto')),
                ('custo_p', models.IntegerField(db_column='Custo_p', verbose_name='Custo do produto')),
                ('preco_p', models.IntegerField(db_column='Preco_p', verbose_name='Valor de venda')),
                ('vender', models.BooleanField(default=True, verbose_name='Vender ?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('nome_f', models.ForeignKey(db_column='Nome_F', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_p'],
            },
        ),
    ]
