# Generated by Django 2.0.3 on 2018-05-25 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.IntegerField(db_column='CPF', unique=True, verbose_name='CPF')),
                ('telefone_u', models.IntegerField(db_column='Telefone_U', verbose_name='Telefone')),
                ('endereco_u', models.CharField(db_column='Endereco_U', max_length=255, verbose_name='Endereço')),
                ('news', models.NullBooleanField(db_column='News', verbose_name='Deseja receber novidades ?')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_u',
            field=models.EmailField(blank=True, db_column='Email_U', max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='password', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(db_column='user_name', max_length=100, unique=True, verbose_name='username'),
        ),
    ]
