# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': False, 'ordering': ['nome_p'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
