# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='news',
            field=models.NullBooleanField(db_column='News', default=True, verbose_name='Deseja receber novidades ?'),
        ),
    ]
