# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email_u',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_u',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_name',
            new_name='username',
        ),
    ]
