# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180927_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_u',
            field=models.IntegerField(db_column='Telefone_U', default=True, verbose_name='Telefone'),
        ),
    ]
