# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180401_1212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='Produto',
        ),
    ]
