# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181004_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.IntegerField(db_column='RG', default=1, verbose_name='RG'),
            preserve_default=False,
        ),
    ]
