# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-31 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180827_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colaboradores',
            new_name='Colaborador',
        ),
        migrations.RenameModel(
            old_name='Contratos',
            new_name='Contrato',
        ),
    ]
