# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180831_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sobre nome'),
        ),
    ]
