# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 20:37
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181010_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[core.models.validate_CPF]),
        ),
    ]
