# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180514_1226'),
        ('core', '0002_categoria_imagem'),
    ]

    operations = [
    ]
