# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180827_1647'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set([('carrinho_key', 'produto')]),
        ),
    ]
