# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='itemdopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.Pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='itemdopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Produto', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('cart_key', 'produto')]),
        ),
    ]
