# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20180827_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrinho',
            new_name='Item_carrinho',
        ),
    ]
