# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180827_1647'),
        ('checkout', '0003_auto_20180828_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_carrinho',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='carrinho_key',
            new_name='cart_key',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='preco_p',
            new_name='preco',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('cart_key', 'produto')]),
        ),
    ]
