# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20180831_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_p',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Preço Total'),
            preserve_default=False,
        ),
    ]
