# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20180920_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
    ]
