# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Nº celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_u',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Nº telefone'),
        ),
    ]
